version: "3.8"

services:
  urls-storage:
    image: cassandra:latest
    container_name: urls-storage-db
    command: [ -f ]
    environment:
      CASSANDRA_CLUSTER_NAME: app
    networks:
      - url-network
    ports:
      - "9042:9042"
      - "9160:9160"
      - "7199:7199"
    healthcheck:
      test: [ "CMD-SHELL", "[ $$(nodetool statusgossip) = running ]" ]
      interval: 10s
      timeout: 5s
      retries: 3
    volumes:
      - cassandra_data:/var/lib/cassandra
    ulimits:
      memlock: -1
  app:
    image: virginonline/url-shortener:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: url-shortener-service
    ports:
      - '8083:8083'
    networks:
      - url-network
    environment:
      CASSANDRA_DATACENTER: datacenter1
      CASSANDRA_KEYSPACE: links
      CASSANDRA_CONTACT_POINTS: "urls-storage:9042"
      CASSANDRA_USER: cassandra
      CASSANDRA_PASSWORD: cassandra
    depends_on:
      urls-storage:
        condition: service_healthy

  cassandra-ui:
    image: ipushc/cassandra-web
    container_name: cassandra-webui
    ports:
      - '3001:3001'
    environment:
      HOST_PORT: ":3001"
      CASSANDRA_HOST: urls-storage
      CASSANDRA_PORT: 9042
      CASSANDRA_USER: cassandra
      CASSANDRA_PASSWORD: cassandra
    networks:
      - url-network

networks:
  url-network:

volumes:
  cassandra_data:
    driver: local