server:
  port: 8083

spring:
  config:
    import: optional:file:.env[.properties]
  main:
    banner-mode: off
  application:
    name: url-shortener-service
  cassandra:
    port: 9042
    keyspace-name: ${CASSANDRA_KEYSPACE}
    connection:
      connect-timeout: 30s
      init-query-timeout: 10s
    request:
      timeout: 10s
    contact-points: ${CASSANDRA_CONTACT_POINTS}
    local-datacenter: ${CASSANDRA_DATACENTER}
    schema-action: create_if_not_exists

  data:
    redis:
      port: 6379
      host: ${REDIS_HOST}
  cache:
    type: redis
    cache-names: redis-cache
    redis:
      time-to-live: ${REDIS_TIME_TO_ALIVE}
      cache-null-values: false
management:
  endpoints:
    web:
      exposure:
        include: "*"

app:
  url-length: 8