server:
  port: 8083
spring:
  application:
    name: url-shortener-service
  cassandra:
    port: 9042
    local-datacenter: datacenter1
    keyspace-name: links
    schema-action: create-if-not-exists
    connection:
      connect-timeout: 30s
      init-query-timeout: 10s
    request:
      timeout: 10s
    contact-points: urls-storage-db
